#!/usr/bin/env python3
"""
One-time build step: extract every translatable English string from the
site's HTML pages, translate EN -> AR with deep-translator (Google backend),
and write a static dictionary to js/translations.js.

Re-run this only when the English content changes:
    python3 build_arabic.py
"""
import glob, json, re, sys
from bs4 import BeautifulSoup, NavigableString, Comment
from deep_translator import GoogleTranslator

SKIP_PARENT_TAGS = {"script", "style", "title", "head"}
EMAIL_OR_URL = re.compile(r"[@]|https?://|www\.")

def norm(s: str) -> str:
    """Collapse whitespace + strip. MUST match the JS norm() in i18n.js."""
    return re.sub(r"\s+", " ", s).strip()

def translatable(text: str) -> bool:
    t = norm(text)
    if len(t) < 2:
        return False
    if not re.search(r"[A-Za-z]", t):      # skip emoji / numbers / symbols only
        return False
    if EMAIL_OR_URL.search(t):             # skip emails and URLs
        return False
    return True

def collect(soup: BeautifulSoup, strings: set):
    body = soup.body
    if body is None:
        return
    # visible text nodes
    for node in body.find_all(string=True):
        if isinstance(node, Comment):
            continue
        parent = node.parent
        if parent is None or parent.name in SKIP_PARENT_TAGS:
            continue
        # skip the language toggle button's own label
        if parent.has_attr("class") and "lang-toggle" in parent.get("class", []):
            continue
        if translatable(str(node)):
            strings.add(norm(str(node)))
    # input / textarea placeholders
    for el in body.select("[placeholder]"):
        ph = el.get("placeholder", "")
        if translatable(ph):
            strings.add(norm(ph))

def main():
    files = sorted(glob.glob("*.html"))
    if not files:
        print("No HTML files found.", file=sys.stderr)
        sys.exit(1)

    strings = set()
    for f in files:
        with open(f, encoding="utf-8") as fh:
            collect(BeautifulSoup(fh.read(), "html.parser"), strings)

    items = sorted(strings)
    print(f"Collected {len(items)} unique strings from {len(files)} pages.")

    translator = GoogleTranslator(source="en", target="ar")
    mapping = {}
    # translate in modest batches to stay well within request limits
    BATCH = 20
    for i in range(0, len(items), BATCH):
        chunk = items[i:i + BATCH]
        out = translator.translate_batch(chunk)
        for en, ar in zip(chunk, out):
            if ar and norm(ar):
                mapping[en] = ar
        print(f"  translated {min(i + BATCH, len(items))}/{len(items)}")

    payload = "window.AR_TRANSLATIONS = " + json.dumps(mapping, ensure_ascii=False, indent=2) + ";\n"
    with open("js/translations.js", "w", encoding="utf-8") as fh:
        fh.write("/* Auto-generated by build_arabic.py — do not edit by hand. */\n")
        fh.write(payload)
    print(f"Wrote js/translations.js with {len(mapping)} entries.")

if __name__ == "__main__":
    main()
